services:
  - type: web
    name: CreditCardImageDetection
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 4 --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: true
